apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  selector:
    app: ftps
  ports:
    - name:  ftps
      port:  21
      targetPort: 21
      protocol: TCP
    - name:  active-con
      port:  20
      targetPort: 20
      protocol: TCP
    - name:  pass-con
      port:  40000
      targetPort: 40000
      protocol: TCP
